# coding: utf-8
TERMS = {'c#': None, 'css': None, 'scss': None, 'ab': None, 'abap': None, 'able': None, 'access': None,
         'accounts': None, 'ace': None, 'acl': None, 'acs': None, 'actionscript': None, 'activex': None, 'ad': None,
         'ada': None, 'adf': None, 'admin': None, 'adsl': None, 'advantage': None, 'ag': None, 'agavi': None,
         'agile': None, 'ajax': None, 'alef': None, 'alfa': None, 'alfresco': None, 'algorithms': None, 'altium': None,
         'amazon': None, 'amp': None, 'amsterdam': None, 'analytics': None, 'analyzer': None, 'android': None,
         'angular': None, 'angularjs': None, 'ansi': None, 'ansible': None, 'ant': None, 'antivirus': None, 'aop': None,
         'ap': None, 'apache': None, 'api': None, 'apis': None, 'apl': None, 'app': None, 'appcelerator': None,
         'applications': None, 'apps': None, 'arangodb': None, 'arcgis': None, 'architect': None, 'architecture': None,
         'archive': None, 'arduino': None, 'ariba': None, 'arm': None, 'art': None, 'as': None, 'asana': None,
         'asf': None, 'asp': None, 'aspectj': None, 'asr': None, 'assemblies': None, 'assembly': None,
         'associates': None, 'atc': None, 'atg': None, 'atlas': None, 'atlassian': None, 'atm': None, 'atos': None,
         'aurora': None, 'autocad': None, 'autodesk': None, 'autoit': None, 'automated': None, 'automation': None,
         'avant': None, 'awk': None, 'ax': None, 'axis': None, 'azure': None, 'baan': None, 'backoffice': None,
         'backup': None, 'bacula': None, 'bancos': None, 'bank': None, 'banking': None, 'bash': None, 'bds': None,
         'bea': None, 'bean': None, 'bi': None, 'bigquery': None, 'bing': None, 'biology': None, 'birt': None,
         'bits': None, 'bl': None, 'blender': None, 'blog': None, 'blue': None, 'bluemix': None, 'bluetooth': None,
         'board': None, 'book': None, 'boost': None, 'boot': None, 'bootstrap': None, 'borland': None,
         'brainstorming': None, 'bridge': None, 'browser': None, 'browserify': None, 'browsers': None, 'brutos': None,
         'bsd': None, 'build': None, 'builder': None, 'builders': None, 'building': None, 'bus': None, 'business': None,
         'bw': None, 'c': None, 'cabos': None, 'cache': None, 'caching': None, 'cad': None, 'cae': None,
         'cakephp': None, 'call': None, 'camera': None, 'campus': None, 'canvas': None, 'cascading': None,
         'cassandra': None, 'cat': None, 'catalog': None, 'catalyst': None, 'cc': None, 'ccs': None, 'cd': None,
         'ce': None, 'cfml': None, 'cgi': None, 'chain': None, 'channel': None, 'chart': None, 'charts': None,
         'chat': None, 'check': None, 'checking': None, 'chemistry': None, 'chrome': None, 'cics': None, 'cisco': None,
         'citrix': None, 'class': None, 'clean': None, 'cli': None, 'client': None, 'clipper': None, 'clojure': None,
         'closure': None, 'cloud': None, 'cloudera': None, 'clr': None, 'cluster': None, 'clustering': None,
         'cmake': None, 'cms': None, 'coat': None, 'coaxial': None, 'cobol': None, 'cockpit': None, 'code': None,
         'codeigniter': None, 'codewarrior': None, 'coffeescript': None, 'cognos': None, 'coherence': None,
         'coherent': None, 'coldfusion': None, 'collaborate': None, 'collaboration': None, 'collaborative': None,
         'collection': None, 'color': None, 'comarch': None, 'comit': None, 'command': None, 'commerce': None,
         'commercial': None, 'common': None, 'communication': None, 'communications': None, 'community': None,
         'commvault': None, 'compact': None, 'company': None, 'compilers': None, 'compliance': None, 'component': None,
         'components': None, 'composer': None, 'composite': None, 'computadores': None, 'computer': None,
         'computing': None, 'concept': None, 'configuration': None, 'confluence': None, 'connect': None,
         'connected': None, 'connections': None, 'console': None, 'construct': None, 'construction': None,
         'consulting': None, 'conta': None, 'container': None, 'content': None, 'continuous': None, 'contribute': None,
         'control': None, 'converter': None, 'copy': None, 'cordova': None, 'core': None, 'corel': None,
         'coroutines': None, 'corpora': None, 'corporation': None, 'cost': None, 'costing': None, 'courier': None,
         'cpu': None, 'crane': None, 'crc': None, 'created': None, 'createjs': None, 'creative': None, 'creator': None,
         'crm': None, 'cross': None, 'crystal': None, 'csc': None, 'csp': None, 'cucumber': None, 'custom': None,
         'customer': None, 'cut': None, 'cvs': None, 'cwi': None, 'cxf': None, 'cycle': None, 'cygwin': None,
         'dao': None, 'dart': None, 'database': None, 'databases': None, 'datastore': None, 'db': None, 'dbmail': None,
         'dbms': None, 'dd': None, 'ddd': None, 'deb': None, 'debian': None, 'debug': None, 'debugger': None,
         'debuggers': None, 'debugging': None, 'dec': None, 'decoupling': None, 'deep': None, 'defender': None,
         'defense': None, 'dell': None, 'delphi': None, 'dependency': None, 'deployment': None, 'description': None,
         'design': None, 'designer': None, 'desk': None, 'desktop': None, 'developer': None, 'development': None,
         'devexpress': None, 'device': None, 'devices': None, 'dhtmlx': None, 'diagrama': None, 'diagrams': None,
         'digital': None, 'dimensional': None, 'director': None, 'directory': None, 'directx': None, 'diretrizes': None,
         'disco': None, 'discoverer': None, 'disk': None, 'disks': None, 'distributed': None, 'distribution': None,
         'django': None, 'dms': None, 'doctrine': None, 'document': None, 'documents': None, 'dojo': None,
         'dolibarr': None, 'dos': None, 'dot': None, 'double': None, 'dovecot': None, 'draw': None, 'drawing': None,
         'dream': None, 'dreamweaver': None, 'drive': None, 'driver': None, 'drm': None, 'drools': None, 'drupal': None,
         'dwr': None, 'dynamic': None, 'dynamics': None, 'easy': None, 'easymock': None, 'ec': None, 'eclipse': None,
         'ecmascript': None, 'edge': None, 'edit': None, 'edition': None, 'editor': None, 'educational': None,
         'ee': None, 'effects': None, 'ehcache': None, 'el': None, 'electronic': None, 'elixir': None, 'embedded': None,
         'emc': None, 'emr': None, 'encoder': None, 'engine': None, 'engineering': None, 'engines': None,
         'enterprise': None, 'entertainment': None, 'entourage': None, 'environment': None, 'environments': None,
         'eps': None, 'equipment': None, 'ericsson': None, 'erlang': None, 'erp': None, 'es': None, 'esb': None,
         'estimation': None, 'ethernet': None, 'european': None, 'event': None, 'everything': None, 'evidence': None,
         'evolution': None, 'exadata': None, 'exasol': None, 'excel': None, 'exchange': None, 'exec': None,
         'executor': None, 'experian': None, 'expert': None, 'explorer': None, 'express': None, 'expression': None,
         'expressions': None, 'ext': None, 'extended': None, 'extensible': None, 'extensions': None, 'extranet': None,
         'extreme': None, 'ez': None, 'facebook': None, 'facelets': None, 'faces': None, 'facility': None,
         'factor': None, 'factory': None, 'fedora': None, 'ferramentas': None, 'fetch': None, 'ffmpeg': None,
         'file': None, 'filemaker': None, 'filzip': None, 'financial': None, 'find': None, 'finger': None,
         'firebird': None, 'firefox': None, 'fireworks': None, 'fl': None, 'flash': None, 'flask': None, 'flex': None,
         'flow': None, 'fluentd': None, 'flyback': None, 'focus': None, 'font': None, 'fontes': None, 'force': None,
         'foreman': None, 'format': None, 'forms': None, 'fortran': None, 'foundation': None, 'foxpro': None,
         'fpga': None, 'framework': None, 'frameworks': None, 'francisco': None, 'free': None, 'freebsd': None,
         'freedom': None, 'freehand': None, 'freeipa': None, 'freelancer': None, 'freemind': None, 'front': None,
         'ftp': None, 'fujitsu': None, 'fusion': None, 'game': None, 'gap': None, 'gas': None, 'gate': None,
         'gateway': None, 'gear': None, 'general': None, 'generators': None, 'genesys': None, 'genexus': None,
         'gerenciador': None, 'gerenciadores': None, 'ghost': None, 'gimp': None, 'gis': None, 'git': None,
         'github': None, 'gl': None, 'glasgow': None, 'glassfish': None, 'gliffy': None, 'global': None, 'gnu': None,
         'go': None, 'golive': None, 'gooddata': None, 'google': None, 'governance': None, 'gp': None, 'grails': None,
         'graph': None, 'graphics': None, 'grc': None, 'green': None, 'greenplum': None, 'grid': None, 'groove': None,
         'groovy': None, 'group': None, 'groups': None, 'gui': None, 'guidance': None, 'gwt': None, 'hadoop': None,
         'hana': None, 'hat': None, 'hbase': None, 'hc': None, 'health': None, 'healthcare': None, 'hf': None,
         'highcharts': None, 'hornetq': None, 'hortonworks': None, 'host': None, 'hosting': None, 'hp': None,
         'hr': None, 'html': None, 'htmlunit': None, 'http': None, 'httpunit': None, 'hxd': None, 'hybrid': None,
         'hybris': None, 'hyperion': None, 'iar': None, 'ibm': None, 'icefaces': None, 'icon': None, 'id': None,
         'ide': None, 'idea': None, 'identity': None, 'idle': None, 'idm': None, 'ignite': None, 'ii': None,
         'iis': None, 'illustrator': None, 'images': None, 'imap': None, 'implementations': None, 'ims': None,
         'inc': None, 'incentive': None, 'independentes': None, 'indesign': None, 'industrial': None, 'infopath': None,
         'information': None, 'informix': None, 'infragistics': None, 'infrastructure': None, 'injection': None,
         'inkscape': None, 'insight': None, 'instagram': None, 'instant': None, 'institute': None,
         'instrumentation': None, 'instruments': None, 'insurance': None, 'integrated': None, 'integration': None,
         'intel': None, 'intelligence': None, 'intellij': None, 'interact': None, 'interactive': None,
         'interbase': None, 'interchange': None, 'interface': None, 'interfaces': None, 'intermediate': None,
         'internal': None, 'international': None, 'internet': None, 'interoperability': None, 'intranet': None,
         'inventory': None, 'investigations': None, 'io': None, 'ionic': None, 'ios': None, 'ip': None, 'ipad': None,
         'iphone': None, 'iq': None, 'is': None, 'iso': None, 'items': None, 'itunes': None, 'iv': None, 'j': None,
         'jaas': None, 'james': None, 'janus': None, 'jasmine': None, 'jasper': None, 'jasperreports': None,
         'jato': None, 'java': None, 'javamail': None, 'javaos': None, 'javascript': None, 'javaserver': None,
         'jboss': None, 'jbpm': None, 'jc': None, 'jersey': None, 'jet': None, 'jetty': None, 'jira': None, 'jit': None,
         'jive': None, 'jmx': None, 'job': None, 'johnson': None, 'joomla': None, 'jpa': None, 'jquery': None,
         'js': None, 'jscript': None, 'jsf': None, 'json': None, 'jsonp': None, 'jsp': None, 'juniper': None,
         'junit': None, 'jwt': None, 'jython': None, 'kepler': None, 'kerberos': None, 'kernel': None, 'keycloak': None,
         'kit': None, 'knime': None, 'knockout': None, 'knowledge': None, 'known': None, 'kohana': None, 'kotlin': None,
         'kubernetes': None, 'kudu': None, 'lab': None, 'label': None, 'laboratory': None, 'labs': None, 'ladder': None,
         'lake': None, 'lamp': None, 'language': None, 'languages': None, 'laptop': None, 'laravel': None, 'ldap': None,
         'leaflet': None, 'learn': None, 'ledger': None, 'less': None, 'lesser': None, 'level': None, 'liberty': None,
         'libraries': None, 'library': None, 'libreoffice': None, 'license': None, 'liferay': None, 'lift': None,
         'light': None, 'limited': None, 'line': None, 'linguagens': None, 'link': None, 'linux': None, 'liquid': None,
         'lodash': None, 'logic': None, 'logical': None, 'logo': None, 'look': None, 'loops': None, 'lotus': None,
         'low': None, 'lua': None, 'lucee': None, 'mac': None, 'machine': None, 'machines': None, 'macintosh': None,
         'macos': None, 'macrium': None, 'macro': None, 'macromedia': None, 'made': None, 'magento': None, 'mail': None,
         'mailing': None, 'mainframe': None, 'malware': None, 'managed': None, 'management': None, 'manager': None,
         'manos': None, 'manufacturing': None, 'mapping': None, 'mapreduce': None, 'maps': None, 'mariadb': None,
         'market': None, 'marketing': None, 'markup': None, 'mashups': None, 'mass': None, 'master': None,
         'mathematics': None, 'matlab': None, 'maven': None, 'max': None, 'maya': None, 'mcafee': None, 'mcp': None,
         'me': None, 'measurement': None, 'mellon': None, 'memcached': None, 'mentor': None, 'merchant': None,
         'mercurial': None, 'merlin': None, 'mes': None, 'mesos': None, 'messages': None, 'messaging': None,
         'metadata': None, 'meteor': None, 'michigan': None, 'micro': None, 'microsoft': None, 'microstrategy': None,
         'microsystems': None, 'middleware': None, 'migration': None, 'mind': None, 'minecraft': None, 'miner': None,
         'miranda': None, 'miro': None, 'mit': None, 'mix': None, 'ml': None, 'mobile': None, 'mocha': None,
         'mock': None, 'mockito': None, 'mocks': None, 'model': None, 'modeler': None, 'modeling': None,
         'mongodb': None, 'monitoring': None, 'motion': None, 'motorola': None, 'mozilla': None, 'mq': None,
         'mssql': None, 'mstest': None, 'mt': None, 'multicast': None, 'multidisciplinary': None, 'mustache': None,
         'mvc': None, 'mvp': None, 'mysql': None, 'nagios': None, 'nasa': None, 'native': None, 'nativescript': None,
         'navigator': None, 'nec': None, 'netapp': None, 'netbackup': None, 'netbeans': None, 'netezza': None,
         'netflix': None, 'netherlands': None, 'netiq': None, 'netsuite': None, 'netweaver': None, 'network': None,
         'networking': None, 'networks': None, 'news': None, 'newsql': None, 'nginx': None, 'nhibernate': None,
         'nice': None, 'ninja': None, 'nokia': None, 'norton': None, 'nosql': None, 'notation': None, 'notepad': None,
         'notes': None, 'nova': None, 'now': None, 'nt': None, 'nucleus': None, 'nuget': None, 'nunit': None,
         'oauth': None, 'object': None, 'objects': None, 'odata': None, 'ode': None, 'office': None, 'oil': None,
         'omni': None, 'omnigraffle': None, 'one': None, 'onedrive': None, 'online': None, 'oop': None, 'openbsd': None,
         'opencart': None, 'opengl': None, 'openlayers': None, 'openldap': None, 'openstack': None, 'opera': None,
         'operations': None, 'opnsense': None, 'optimization': None, 'optimized': None, 'optimizing': None,
         'opus': None, 'oracle': None, 'orientdb': None, 'oriented': None, 'orion': None, 'orm': None, 'oscar': None,
         'osgi': None, 'osi': None, 'other': None, 'outlook': None, 'own': None, 'pac': None, 'pack': None,
         'package': None, 'packages': None, 'packaging': None, 'packet': None, 'pages': None, 'paint': None,
         'panasonic': None, 'panorama': None, 'parallel': None, 'partition': None, 'partners': None,
         'partnership': None, 'pascal': None, 'passport': None, 'pat': None, 'path': None, 'pattern': None,
         'patterns': None, 'payara': None, 'payroll': None, 'pc': None, 'pcs': None, 'pdf': None, 'pentaho': None,
         'peoplesoft': None, 'percona': None, 'perl': None, 'persistence': None, 'pfsense': None, 'phalcon': None,
         'philips': None, 'phoenix': None, 'photoshop': None, 'php': None, 'phpunit': None, 'pi': None, 'pip': None,
         'pix': None, 'pixia': None, 'planner': None, 'planning': None, 'plant': None, 'platform': None, 'play': None,
         'player': None, 'plugin': None, 'plus': None, 'poi': None, 'point': None, 'polymer': None, 'pop': None,
         'portal': None, 'portfolio': None, 'pos': None, 'posix': None, 'post': None, 'postfix': None,
         'postgresql': None, 'power': None, 'powerpoint': None, 'ppc': None, 'pr': None, 'premiere': None,
         'preprocessor': None, 'presentation': None, 'presenter': None, 'press': None, 'primefaces': None, 'pro': None,
         'process': None, 'processing': None, 'processor': None, 'procurement': None, 'professional': None,
         'profiler': None, 'profitability': None, 'program': None, 'programming': None, 'programs': None,
         'progress': None, 'project': None, 'projects': None, 'projectwise': None, 'proprietary': None, 'protect': None,
         'protection': None, 'protector': None, 'protocol': None, 'protocolos': None, 'protocols': None,
         'prototype': None, 'prototyping': None, 'proxy': None, 'ps': None, 'published': None, 'pulse': None,
         'purchasing': None, 'putty': None, 'py': None, 'pycharm': None, 'pyqt': None, 'python': None, 'qa': None,
         'qmail': None, 'qml': None, 'qt': None, 'quantitative': None, 'query': None, 'quest': None, 'qunit': None,
         'quod': None, 'r': None, 'rack': None, 'rad': None, 'rails': None, 'ram': None, 'range': None, 'rapid': None,
         'raspberry': None, 'raster': None, 'rational': None, 'ravendb': None, 'rdbms': None, 'react': None,
         'reactjs': None, 'reader': None, 'real': None, 'realm': None, 'receivable': None, 'recognition': None,
         'recovery': None, 'red': None, 'rede': None, 'redis': None, 'redmine': None, 'redshift': None, 'redux': None,
         'reengineering': None, 'refactoring': None, 'reference': None, 'referências': None, 'refinery': None,
         'reflect': None, 'regression': None, 'regular': None, 'relationship': None, 'remoting': None,
         'rendering': None, 'report': None, 'reporting': None, 'reports': None, 'repository': None, 'requests': None,
         'research': None, 'resources': None, 'restful': None, 'retail': None, 'rewriting': None, 'rexx': None,
         'rfc': None, 'rich': None, 'richfaces': None, 'rig': None, 'risc': None, 'rise': None, 'risk': None,
         'rm': None, 'robot': None, 'rspec': None, 'rt': None, 'ruby': None, 'rules': None, 'run': None,
         'runtime': None, 'rvm': None, 's': None, 'safari': None, 'safety': None, 'sage': None, 'salt': None,
         'samba': None, 'sametime': None, 'saml': None, 'samsung': None, 'san': None, 'sanity': None, 'sap': None,
         'sas': None, 'sass': None, 'satellite': None, 'scada': None, 'scala': None, 'scalable': None,
         'scheduler': None, 'science': None, 'scm': None, 'scoring': None, 'scp': None, 'scratch': None, 'screen': None,
         'script': None, 'scripting': None, 'sdk': None, 'sds': None, 'se': None, 'seam': None, 'sector': None,
         'secure': None, 'security': None, 'selenium': None, 'self': None, 'semantic': None, 'sencha': None,
         'sendmail': None, 'sense': None, 'sensor': None, 'server': None, 'servers': None, 'service': None,
         'services': None, 'servlet': None, 'servlets': None, 'session': None, 'sftp': None, 'sgi': None, 'sh': None,
         'share': None, 'shared': None, 'sharepoint': None, 'sharing': None, 'sheets': None, 'shell': None,
         'shipping': None, 'shopping': None, 'should': None, 'shrink': None, 'siemens': None, 'signalr': None,
         'silex': None, 'silvia': None, 'sim': None, 'simple': None, 'simulation': None, 'sinatra': None,
         'single': None, 'sites': None, 'sketch': None, 'skype': None, 'sl': None, 'slack': None, 'slackware': None,
         'sleuth': None, 'slide': None, 'small': None, 'smallworld': None, 'smartphones': None, 'sms': None,
         'snap': None, 'soa': None, 'soap': None, 'soapui': None, 'softlayer': None, 'software': None, 'solaris': None,
         'solution': None, 'solutions': None, 'sophos': None, 'sound': None, 'source': None, 'sources': None,
         'sourcesafe': None, 'sparc': None, 'spark': None, 'specification': None, 'specifications': None,
         'spectrum': None, 'speech': None, 'spin': None, 'splunk': None, 'spock': None, 'spring': None, 'spss': None,
         'sql': None, 'sqlalchemy': None, 'sqlite': None, 'srm': None, 'ssh': None, 'st': None, 'stacks': None,
         'standard': None, 'standards': None, 'stateless': None, 'statistical': None, 'steel': None, 'stellar': None,
         'stock': None, 'storage': None, 'storm': None, 'story': None, 'strategic': None, 'street': None,
         'structural': None, 'structures': None, 'struts': None, 'studio': None, 'study': None, 'sublime': None,
         'subversion': None, 'successfactors': None, 'suite': None, 'suites': None, 'sun': None, 'super': None,
         'supply': None, 'supported': None, 'swap': None, 'sweet': None, 'swift': None, 'switch': None,
         'switchyard': None, 'swt': None, 'sybase': None, 'symantec': None, 'symfony': None, 'symphony': None,
         'sysinternals': None, 'system': None, 'systems': None, 'systemverilog': None, 't': None, 'tableau': None,
         'tablet': None, 'tablets': None, 'talend': None, 'tap': None, 'tape': None, 'tcl': None, 'tcp': None,
         'team': None, 'teams': None, 'teamviewer': None, 'technologies': None, 'technology': None,
         'telecommunications': None, 'telephony': None, 'telnet': None, 'telon': None, 'templating': None,
         'teradata': None, 'terminal': None, 'terminals': None, 'test': None, 'testing': None, 'testng': None,
         'tests': None, 'tex': None, 'text': None, 'thin': None, 'thread': None, 'threading': None, 'threads': None,
         'threat': None, 'thunderbird': None, 'thymeleaf': None, 'tibco': None, 'tiles': None, 'tim': None,
         'titanium': None, 'tivoli': None, 'tizen': None, 'tom': None, 'tomcat': None, 'toolkit': None,
         'toolkits': None, 'tools': None, 'tor': None, 'tornado': None, 'total': None, 'touch': None, 'tpc': None,
         'trac': None, 'trace': None, 'tracking': None, 'tradutores': None, 'train': None, 'training': None,
         'transact': None, 'transaction': None, 'transactions': None, 'transfer': None, 'transmission': None,
         'travis': None, 'trees': None, 'trello': None, 'tutor': None, 'tuxedo': None, 'tv': None, 'twig': None,
         'twitter': None, 'typescript': None, 'ubuntu': None, 'udp': None, 'ui': None, 'umbraco': None, 'uml': None,
         'understanding': None, 'unified': None, 'unit': None, 'unity': None, 'university': None, 'unix': None,
         'ups': None, 'url': None, 'utilities': None, 'uwsgi': None, 'vaadin': None, 'valgrind': None,
         'validation': None, 'varnish': None, 'vb': None, 'vbscript': None, 'vector': None, 'vega': None,
         'velocity': None, 'version': None, 'versions': None, 'vertica': None, 'viewer': None, 'vim': None,
         'virtual': None, 'virtualbox': None, 'virtualization': None, 'visio': None, 'vision': None, 'visit': None,
         'visual': None, 'visualage': None, 'visualization': None, 'visualvm': None, 'vm': None, 'vms': None,
         'vmware': None, 'vo': None, 'voice': None, 'vraptor': None, 'vs': None, 'vsts': None, 'waf': None,
         'warehouse': None, 'watch': None, 'watson': None, 'wave': None, 'wcm': None, 'web': None, 'webcenter': None,
         'webdriver': None, 'webgl': None, 'webkit': None, 'weblogic': None, 'webmail': None, 'website': None,
         'websites': None, 'websocket': None, 'websphere': None, 'while': None, 'white': None, 'why': None,
         'wicket': None, 'wide': None, 'widget': None, 'widgets': None, 'wifi': None, 'wildfly': None, 'williams': None,
         'wind': None, 'window': None, 'windows': None, 'wine': None, 'wink': None, 'wireless': None, 'wireshark': None,
         'wm': None, 'wms': None, 'word': None, 'wordpress': None, 'workbench': None, 'workflow': None,
         'workplace': None, 'workshop': None, 'workspace': None, 'workstation': None, 'wpf': None, 'writer': None,
         'wsdl': None, 'xamarin': None, 'xaml': None, 'xapps': None, 'xcode': None, 'xdebug': None, 'xfce': None,
         'xhtml': None, 'xmind': None, 'xml': None, 'xp': None, 'xpediter': None, 'xquery': None, 'xslt': None,
         'xunit': None, 'yaml': None, 'yeoman': None, 'yii': None, 'your': None, 'youtube': None, 'zend': None,
         'zimbra': None, 'zk': None, 'zoho': None, 'zoom': None}
